### ISSUE TITLE
In Chrome 103, ModHeader is no longer altering the origin header.

### ISSUE THREAD

**Issue by samuelhar** [modheader/modheader#122] opened 2022-07-25 21:24 UTC
My chrome recently updated to version 103.0.5060.134, and it now seems that ModHeader is no longer to alter the 'origin' header in Chrome. Not sure if this an issue that can be fixed but I would be interested if others are noticing the same issue.

**Comment by hao1300** [comment] 2022-07-26 21:26
@samuelhar I am also using 103.0.5060.134 on Windows 11, and I can still modify it just fine. Can you try modifying the 'origin' header and see if the modified value shows up in https://modheader.com/headers? Do you have other filters set up?

**Comment by samuelhar** [comment] 2022-07-26 21:32
It doesn’t show up for me on request headers either. It’s very weird, no
filters are set up just a simple function to replace the origin header with
another value.

**Comment by hao1300** [comment] 2022-07-26 21:56
That is very odd. I will need some more details to debug further. @samuelhar Can you share with me the followings?
1, Export your profile and share with me the URL or JSON. (replace any sensitive value with * if necessary)
2, Can you tell me the URLs where you are repro-ing this issue?
3, Can you try ModHeader on Firefox https://addons.mozilla.org/en-US/firefox/addon/modheader-firefox/ and see if it has the same issue?

**Comment by sajTempler** [comment] 2022-08-15 10:03
It also stopped working for me with latest chrome. (Im on latest ModHeader version as well)

Looking at `https://modheader.com/headers` it seem to append just one header (not the two)

![image](https://user-images.githubusercontent.com/7117333/184616446-54e334f8-a62e-4683-8c45-d1b2e233b55c.png)

for local API call neither is altered
call from e.g. Postman with headers set works just fine

**Comment by hao1300** [comment] 2022-08-15 11:58
@sajTempler - This is strange. It appears that `x-user_id` is being sent in the network request, but it is not being received by my backend. I suspect this is because AWS CloudFront (where I host my server) is stripping out request headers with `_` before forwarding it to my backend. Changing to `x-user-id` and it would appear. Using `x-consumer_username` and it would not show up to my backend. That said, it appears that ModHeader is still modifying the request header correctly. The issue is on my website, not the extension.
![Screen Shot 2022-08-15 at 6 50 05 AM](https://user-images.githubusercontent.com/25540575/184630385-aa6d9188-c73f-4605-9094-0fd16163450e.png)

If ModHeader works for POST and _not_ for GET, there is a high probability that your GET request was served from cache. Have you tried disabling cache in the network panel? Does this happen on all GET requests for you? Or only on certain URLs?

**Comment by hao1300** [comment] 2022-10-13 20:55
Closing due to lack of activities

**Closed by hao1300** 2022-10-13 20:55 UTC
