### ISSUE TITLE
Headers not included in GET-requests after Chrome 98 

### ISSUE THREAD

**Issue by EvenAR** [modheader/modheader#96] opened 2022-02-07 15:47 UTC
After upgrading from Google Chrome 97.X to 98.0.4758.80 request headers are no longer added on CORS GET requests that are seen as Private Network Access. In our case requests from a site on IP 146.*** to 10.***. As an alternative to ModHeader, when we add the header to `XMLHttpRequest.prototype.send` in Javascript everything works as expected.

More info on Private Network Access: 
- https://developer.chrome.com/blog/private-network-access-update/
- https://developer.chrome.com/blog/private-network-access-preflight/
- https://web.dev/cors-rfc1918-feedback/#what-kinds-of-requests-are-affected

**Comment by hao1300** [comment] 2022-05-09 20:16
@EvenAR - I am not familiar with Private Network Access. Do you have any suggestion on how I can repro this?

**Comment by hao1300** [comment] 2022-07-18 11:43
Closing as I am not able to reproduce

**Closed by hao1300** 2022-07-18 11:43 UTC
